# Generated by Django 3.2.3 on 2021-05-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('drinks', 'treats'), ('entrees', 'entrees'), ('treats', 'treats'), ('appetizers', 'appetizers')], max_length=60),
        ),
    ]
